/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import dao.ClientDao;
import dao.ExportPdf;
import dao.ExportExcel;
import model.Client;

/**
 *
 * @author hirwa
 */
public class ClientForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form ClientForm
     */
    public ClientForm() {
        initComponents();
        populateClient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        regNoField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        lastNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmailAddressField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        searchClientRegNo = new javax.swing.JTextField();
        UpdateButton = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        clientCategoryComboBox = new javax.swing.JComboBox<>();
        exportPdfButton = new javax.swing.JButton();
        exportExcelButton = new javax.swing.JButton();
        PhotoPanel = new javax.swing.JPanel();
        PhotoLabel = new javax.swing.JLabel();
        BrowsePhotoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        clientTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Client");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(1, 1, 1))); // NOI18N

        jLabel1.setText("First Name");

        jLabel2.setText("Reg No");

        jLabel3.setText("Last Name");

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Phone Number");

        jLabel5.setText("Client Category");

        jLabel6.setText("Email");

        jLabel7.setText("Search by Client Regno");

        searchClientRegNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchClientRegNoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchClientRegNoKeyReleased(evt);
            }
        });

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        SaveButton.setText("Save");
        SaveButton.setName(""); // NOI18N
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        clientCategoryComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Staff", "Student", "External" }));

        exportPdfButton.setText("Export Pdf");
        exportPdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportPdfButtonActionPerformed(evt);
            }
        });

        exportExcelButton.setText("Export Excel");
        exportExcelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportExcelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lastNameField)
                            .addComponent(firstNameField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(regNoField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(EmailAddressField)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                            .addComponent(clientCategoryComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchClientRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(SaveButton)
                        .addGap(27, 27, 27)
                        .addComponent(UpdateButton)
                        .addGap(26, 26, 26)
                        .addComponent(deleteButton)
                        .addGap(18, 18, 18)
                        .addComponent(exportPdfButton)
                        .addGap(18, 18, 18)
                        .addComponent(exportExcelButton)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(searchClientRegNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(clientCategoryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(EmailAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(regNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateButton)
                    .addComponent(deleteButton)
                    .addComponent(SaveButton)
                    .addComponent(exportPdfButton)
                    .addComponent(exportExcelButton))
                .addGap(23, 23, 23))
        );

        PhotoPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Photo"));

        javax.swing.GroupLayout PhotoPanelLayout = new javax.swing.GroupLayout(PhotoPanel);
        PhotoPanel.setLayout(PhotoPanelLayout);
        PhotoPanelLayout.setHorizontalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );
        PhotoPanelLayout.setVerticalGroup(
            PhotoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PhotoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
        );

        BrowsePhotoButton.setText("Browse");
        BrowsePhotoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrowsePhotoButtonActionPerformed(evt);
            }
        });

        clientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RegNo", "First Name", "Last Name", "Phone Number", "Client Category", "Email"
            }
        ));
        jScrollPane2.setViewportView(clientTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BrowsePhotoButton))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PhotoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BrowsePhotoButton))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        Client c = new Client();
        
        c.setRegno(regNoField.getText());
        c.setFirstname(firstNameField.getText());
        c.setLastname(lastNameField.getText());
        c.setPhonenumber(phoneNumberField.getText());
        c.setClientcategory(clientCategoryComboBox.getSelectedItem().toString());
        c.setEmailaddress(EmailAddressField.getText());
        c.setPhoto(path);
        
        ClientDao cdao = new ClientDao();
        cdao.updateClient(c);
        
        populateClient();
        resetFields();
        JOptionPane.showMessageDialog(this, "Data Saved!!");
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here
        Client c = new Client();
        
        c.setRegno(regNoField.getText());
        c.setFirstname(firstNameField.getText());
        c.setLastname(lastNameField.getText());
        c.setPhonenumber(phoneNumberField.getText());
        c.setClientcategory(clientCategoryComboBox.getSelectedItem().toString());
        c.setEmailaddress(EmailAddressField.getText());
        c.setPhoto(path);
        
        ClientDao cdao = new ClientDao();
        cdao.saveClient(c);
        
        populateClient();
        resetFields();
        JOptionPane.showMessageDialog(this, "Data Saved!!");
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        Client c = new Client(regNoField.getText());
        ClientDao cdao = new ClientDao();
        cdao.deleteClient(c);
        
        populateClient();
        resetFields();
        JOptionPane.showMessageDialog(this, "Data Deleted!!");
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void searchClientRegNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchClientRegNoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_searchClientRegNoKeyTyped

    String path = null;
    ImageIcon imgicon = null;
    
    private void searchClientRegNoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchClientRegNoKeyReleased
        // TODO add your handling code here:
        ClientDao cdao = new ClientDao();
        List<Client> clients = cdao.findByClientId(searchClientRegNo.getText());
        for(Client c:clients){
            regNoField.setText(c.getRegno());
            firstNameField.setText(c.getFirstname());
            lastNameField.setText(c.getLastname());
            phoneNumberField.setText(c.getPhonenumber());
            clientCategoryComboBox.setSelectedItem(c.getClientcategory());
            EmailAddressField.setText(c.getEmailaddress());
            path = c.getPhoto();
            imgicon = new ImageIcon(path);
            Image image = imgicon.getImage().getScaledInstance(PhotoLabel.getWidth(), PhotoLabel.getHeight(), Image.SCALE_SMOOTH);
            PhotoLabel.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_searchClientRegNoKeyReleased
    
    //This method helps to choose images
    private void BrowsePhotoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrowsePhotoButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        if(file.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){
            File myfile = file.getSelectedFile();
            path = myfile.getAbsolutePath();
            imgicon = new ImageIcon(path);
            Image image = imgicon.getImage().getScaledInstance(PhotoLabel.getWidth(), PhotoLabel.getHeight(), Image.SCALE_SMOOTH);
            PhotoLabel.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_BrowsePhotoButtonActionPerformed

    private void exportPdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportPdfButtonActionPerformed
        // TODO add your handling code here:
        ExportPdf pdf = new ExportPdf();
        pdf.exportPdfData(clientTable);
        JOptionPane.showMessageDialog(this, "The Data Exported to PDF Successfully !!!");
    }//GEN-LAST:event_exportPdfButtonActionPerformed

    private void exportExcelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportExcelButtonActionPerformed
        // TODO add your handling code here:
        ExportExcel m = new ExportExcel();
        m.export(clientTable,"operation");
        JOptionPane.showMessageDialog(this, "The Data Exported to Excel Successfully !!!");
    }//GEN-LAST:event_exportExcelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BrowsePhotoButton;
    private javax.swing.JTextField EmailAddressField;
    private javax.swing.JLabel PhotoLabel;
    private javax.swing.JPanel PhotoPanel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JComboBox<String> clientCategoryComboBox;
    private javax.swing.JTable clientTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton exportExcelButton;
    private javax.swing.JButton exportPdfButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JTextField regNoField;
    private javax.swing.JTextField searchClientRegNo;
    // End of variables declaration//GEN-END:variables

    //This method is for putting data into the table
    private void populateClient(){
        //Bellow on the first line we create titles of our data.
        String colnames[] = {"REGNO","FIRSTNAME","LASTNAME","PHONE NUMBER","CLIENT CATEGORY","EMAIL ADDRESS","PHOTO"};
        
        DefaultTableModel model = (DefaultTableModel) clientTable.getModel();
        model.setRowCount(0);
        model.setColumnIdentifiers(colnames);//Here we put titles in the table
        
        ClientDao cdao = new ClientDao();
        List<Client> clients = cdao.displayClient();
        clientTable.getColumn("PHOTO").setCellRenderer(new myTableCellRender());
        for(Client c:clients){
            JLabel lb = new JLabel();
            imgicon = new ImageIcon(c.getPhoto());
            Image image = imgicon.getImage().getScaledInstance(60, 60, Image.SCALE_DEFAULT);
            lb.setIcon(new ImageIcon(image));
            Object[] obj = {c.getRegno(), c.getFirstname(), c.getLastname(), c.getPhonenumber(), c.getClientcategory(), c.getEmailaddress(), lb};
            model.addRow(obj);
        }
        clientTable.setModel(model);
    }
    
    //This class contains a method which creates a structure of the table so that we can even add things like images.
    class myTableCellRender implements TableCellRenderer {
        @Override
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column){
            TableColumn tc = clientTable.getColumn("PHOTO");
            tc.setMaxWidth(60);
            tc.setMinWidth(60);
            table.setRowHeight(70);
            return (Component) value;
        }
    }
    //This methods resets the field after saving or updating
    public void resetFields(){
        regNoField.setText("");
        firstNameField.setText("");
        lastNameField.setText("");
        phoneNumberField.setText("");
        clientCategoryComboBox.setSelectedItem(0);
        EmailAddressField.setText("");
        PhotoLabel.setIcon(new ImageIcon());
    }
}