/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Faculty;
import Model.Student;
import Model.Gender;
import Utils.StudentUtil;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Service.IstudentService;

/**
 *
 * @author Aime
 */
public class StudentView extends javax.swing.JFrame {

    /**
     * Creates new form ClientView
     */
    DefaultTableModel model;

    DefaultTableModel filtermodel;
    DefaultTableModel filtermod;

    public StudentView() {
        initComponents();
        popclient();
    }

    public void popclient() {
        model = (DefaultTableModel) table.getModel();
        List<Student> clie = new ArrayList<>();
        clie = new Controller.StudentController().stlist();
        for (Student cl : clie) {
            model.insertRow(model.getRowCount(), new Object[]{
                cl.getClientid(), cl.getClientname(), cl.getDob(), cl.getGender(),cl.getFaculty()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        clientid = new javax.swing.JTextField();
        clientname = new javax.swing.JTextField();
        gender = new javax.swing.JComboBox<>();
        save = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        softwareTable = new javax.swing.JTable();
        softList = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        faculty = new javax.swing.JComboBox<>();
        netlist = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        networkingTable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registration Id");

        jLabel2.setText("Date of birth");

        jLabel3.setText(" Name");

        jLabel4.setText("Gender");

        gender.setBackground(new java.awt.Color(240, 240, 240));
        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male" }));

        save.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        save.setText("SAVE");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        Update.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Update.setText("UPDATE");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        Delete.setText("DELETE");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RegId", "Names", "Date of Birth", "Gender", "Faculty"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        softwareTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration Id", "Name", "Faculty"
            }
        ));
        jScrollPane3.setViewportView(softwareTable);

        softList.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        softList.setText("Software");
        softList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                softListActionPerformed(evt);
            }
        });

        jLabel5.setText("Faculty");

        faculty.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "network", "software" }));

        netlist.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        netlist.setText("Networking");
        netlist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netlistActionPerformed(evt);
            }
        });

        networkingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration Id", "Names", "Faculty"
            }
        ));
        jScrollPane4.setViewportView(networkingTable);

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel6.setText("RMI EXAMINATION");

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel7.setText("Filter");

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setText("Software");

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText("Networking");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(21, 21, 21))
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clientid)
                            .addComponent(clientname)
                            .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(faculty, 0, 230, Short.MAX_VALUE)
                            .addComponent(dob, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(70, 70, 70))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(save)
                        .addGap(18, 18, 18)
                        .addComponent(Update)
                        .addGap(18, 18, 18)
                        .addComponent(Delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(49, 49, 49)
                        .addComponent(softList)
                        .addGap(82, 82, 82)
                        .addComponent(netlist))
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(378, 378, 378)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel6)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Update)
                            .addComponent(save)
                            .addComponent(Delete))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(softList)
                                    .addComponent(netlist)
                                    .addComponent(jLabel7))
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(clientid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(clientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(faculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        Student cl = new Student();

        cl.setClientid(clientid.getText());
        cl.setClientname(clientname.getText());
        cl.setDob(dob.getDate());
        if (gender.getSelectedItem().toString().equalsIgnoreCase("female")) {
            cl.setGender(Gender.female);
        }
        
        if (gender.getSelectedItem().toString().equalsIgnoreCase("male")) {
            cl.setGender(Gender.male);
        }
         if (faculty.getSelectedItem().toString().equalsIgnoreCase("network")) {
            cl.setFaculty(Faculty.network);
        }
             if (faculty.getSelectedItem().toString().equalsIgnoreCase("software")) {
            cl.setFaculty(Faculty.software);
        }
        
        IstudentService ics = StudentUtil.getClientService();
        if (ics != null) {
            try {
                ics.delete(cl);
            } catch (RemoteException ex) {
                Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
            }

            System.out.println("Saved...");
        } else {
            System.out.println("Unable to find the server");
        }
        System.exit(0);
    }//GEN-LAST:event_DeleteActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed

        Student cl = new Student();
        String id = clientid.getText();
        
        if(id.length() <=5 ){
            
            
                cl.setClientid(clientid.getText());
                cl.setClientname(clientname.getText());
                cl.setDob(dob.getDate());
                if (gender.getSelectedItem().toString().equalsIgnoreCase("female")) {
                    cl.setGender(Gender.female);
                }
                if (gender.getSelectedItem().toString().equalsIgnoreCase("male")) {
                    cl.setGender(Gender.male);
                }
                if (faculty.getSelectedItem().toString().equalsIgnoreCase("network")) {
                    cl.setFaculty(Faculty.network);
                }
                if (faculty.getSelectedItem().toString().equalsIgnoreCase("software")) {
                    cl.setFaculty(Faculty.software);
                }
                IstudentService ics = StudentUtil.getClientService();
                if (ics != null) {
                    try {
                        ics.save(cl);
                    } catch (RemoteException ex) {
                        Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    System.out.println("Saved...");
                } else {
                    System.out.println("Unable to find the server");
                }
                System.exit(0);

        }else{
            JOptionPane.showMessageDialog(null, "Reg number must be 5 digits or less.", "Reg Number error.", JOptionPane.ERROR_MESSAGE);
        }
           

    }//GEN-LAST:event_saveActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        Student cl = new Student();
        cl.setClientid(clientid.getText());
        cl.setClientname(clientname.getText());
        cl.setDob(dob.getDate());
        if (gender.getSelectedItem().toString().equalsIgnoreCase("female")) {
            cl.setGender(Gender.female);
        }
        if (gender.getSelectedItem().toString().equalsIgnoreCase("male")) {
            cl.setGender(Gender.male);
        }
          if (faculty.getSelectedItem().toString().equalsIgnoreCase("network")) {
            cl.setFaculty(Faculty.network);
        }
             if (faculty.getSelectedItem().toString().equalsIgnoreCase("software")) {
            cl.setFaculty(Faculty.software);
        }
        IstudentService ics = StudentUtil.getClientService();
        if (ics != null) {
            try {
                ics.update(cl);
            } catch (RemoteException ex) {
                Logger.getLogger(StudentView.class.getName()).log(Level.SEVERE, null, ex);
            }

            System.out.println("Saved...");
        } else {
            System.out.println("Unable to find the server");
        }
        System.exit(0);
    }//GEN-LAST:event_UpdateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        model = (DefaultTableModel) table.getModel();
        int row = table.getSelectedRow();
        clientid.setText(model.getValueAt(row, 0).toString());
        clientname.setText(model.getValueAt(row, 1).toString());
        dob.setDate((Date) model.getValueAt(row, 2));
        gender.setSelectedItem(model.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tableMouseClicked

    private void softListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_softListActionPerformed
                
        filtermodel = (DefaultTableModel) softwareTable.getModel();
        List<Student> cli = new ArrayList<>();

        cli = new Controller.StudentController().stlist();
        for (Student client : cli) {
            if (client.getFaculty().toString().equalsIgnoreCase("software")) {
                filtermodel.insertRow(filtermodel.getRowCount(), new Object[]{
                    client.getClientid(), client.getClientname(), client.getFaculty().toString()});
            }
        }


    }//GEN-LAST:event_softListActionPerformed

    private void netlistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netlistActionPerformed

     filtermod = (DefaultTableModel) networkingTable.getModel();
        List<Student> cli = new ArrayList<>();

        cli = new Controller.StudentController().stlist();
        for (Student client : cli) {
            if (client.getFaculty().toString().equalsIgnoreCase("network")) {
                filtermod.insertRow(filtermod.getRowCount(), new Object[]{
                    client.getClientid(), client.getClientname(), client.getFaculty().toString()});
            }
        }
    }//GEN-LAST:event_netlistActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Update;
    private javax.swing.JTextField clientid;
    private javax.swing.JTextField clientname;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JComboBox<String> faculty;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton netlist;
    private javax.swing.JTable networkingTable;
    private javax.swing.JButton save;
    private javax.swing.JButton softList;
    private javax.swing.JTable softwareTable;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
