package model;
// Generated Sep 2, 2021 2:07:15 PM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.Id;




/**
 * Foods generated by hbm2java
 */
@Entity
public class Foods  implements java.io.Serializable {

    @Id
     private int id;
     private String name;
     private String price;

    public Foods() {
    }

	
    public Foods(int id) {
        this.id = id;
    }
    public Foods(int id, String name, String price) {
       this.id = id;
       this.name = name;
       this.price = price;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


