/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vaccination.View;

import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.type.SerializationException;
import vaccination.Controller.VaccineDao;
import vaccination.Model.Vaccine;
import vaccination.Model.VaccineBrands;
import vaccination.Services.IvaccineService;

/**
 *
 * @author hirwa
 */
public class VaccineRegistry extends javax.swing.JInternalFrame {

    /**
     * Creates new form VaccineRegistry
     */
    public VaccineRegistry() {
        initComponents();
        updateVaccineTable();
    }

    public void updateVaccineTable() {
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
        
        VaccineDao vxd = new VaccineDao();
        Vaccine vx = new Vaccine();
        List<Vaccine> vxlist = vxd.findAll(vx);
        
        for (Vaccine vaccine : vxlist) {
            model.insertRow(model.getRowCount(), new Object[] {
                vaccine.getCitizenId(),
                vaccine.getFullnames(),
                vaccine.getPhonenumber(),
                vaccine.getVaccinationstatus(),
                vaccine.getVaccinebrand(),
                vaccine.getVaccinationdate()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        citizenIdField = new javax.swing.JTextField();
        fullnameField = new javax.swing.JTextField();
        phoneNumberField = new javax.swing.JTextField();
        YesStatusRadioButton = new javax.swing.JRadioButton();
        NoStatusRadioButton = new javax.swing.JRadioButton();
        VaccineBrandComboBox = new javax.swing.JComboBox<>();
        VaccinationDateField = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        saveButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        SortingComboBox = new javax.swing.JComboBox<>();
        SortingButton = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Vaccine Registry");

        jLabel1.setText("Citizen ID");

        jLabel2.setText("Full name");

        jLabel3.setText("Phone Number");
        jLabel3.setToolTipText("");

        jLabel4.setText("Vaccinated");

        jLabel5.setText("Vaccine Brand");

        jLabel6.setText("Vaccination Date");

        buttonGroup1.add(YesStatusRadioButton);
        YesStatusRadioButton.setSelected(true);
        YesStatusRadioButton.setText("Yes");
        YesStatusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesStatusRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(NoStatusRadioButton);
        NoStatusRadioButton.setText(" No");
        NoStatusRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoStatusRadioButtonActionPerformed(evt);
            }
        });

        VaccineBrandComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AstraZeneka", "Pfizer", "Moderna" }));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Citizen ID", "Full Name", "Phone Number", "Vaccinattion Status", "Vaccine Brand", "Vaccination Date"
            }
        ));
        jScrollPane1.setViewportView(Table);

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Sort By");

        SortingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "vaccinated", "not-vaccinated" }));

        SortingButton.setText("Sort");
        SortingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortingButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(53, 53, 53))
                                        .addComponent(jLabel2))
                                    .addComponent(jLabel3))
                                .addComponent(jLabel4))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(citizenIdField)
                            .addComponent(fullnameField)
                            .addComponent(phoneNumberField)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(YesStatusRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NoStatusRadioButton))
                            .addComponent(VaccineBrandComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(VaccinationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(saveButton)
                            .addComponent(jLabel7)
                            .addComponent(SortingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SortingButton))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(citizenIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(fullnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(phoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(YesStatusRadioButton)
                    .addComponent(NoStatusRadioButton)
                    .addComponent(SortingComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(VaccineBrandComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(VaccinationDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(SortingButton)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String vaccinationStatus() {
        String status = null;
        if (YesStatusRadioButton.isSelected())
            status = "vaccinated";
        if (NoStatusRadioButton.isSelected())
            status = "not-vaccinated";
        return status;
    }
    
    private void NoStatusRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoStatusRadioButtonActionPerformed
        // TODO add your handling code here:
        VaccineBrandComboBox.setEnabled(false);
        VaccineBrandComboBox.removeAllItems();
        VaccineBrandComboBox.addItem("Null");
    }//GEN-LAST:event_NoStatusRadioButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        try {
            Vaccine vx = new Vaccine();
        
            vx.setCitizenId(citizenIdField.getText());
            vx.setFullnames(fullnameField.getText());
            vx.setPhonenumber(phoneNumberField.getText());
            vx.setVaccinationstatus(vaccinationStatus());
            if(VaccineBrandComboBox.getSelectedItem().toString().equalsIgnoreCase("AstraZeneka")){
                vx.setVaccinebrand(VaccineBrands.AstraZeneka);
            }
            if(VaccineBrandComboBox.getSelectedItem().toString().equalsIgnoreCase("pfizer")){
                vx.setVaccinebrand(VaccineBrands.pfizer);
            }
            if(VaccineBrandComboBox.getSelectedItem().toString().equalsIgnoreCase("Moderna")){
                vx.setVaccinebrand(VaccineBrands.Moderna);
            }
       
            java.sql.Date sqldate = new java.sql.Date(VaccinationDateField.getDate().getTime());
            LocalDate date = sqldate.toLocalDate();
            vx.setVaccinationdate(date);
        
            IvaccineService ivs = new VaccineDao();
            ivs.save(vx);
        
            updateVaccineTable();
            
            JOptionPane.showMessageDialog(this, "Saved Successfully!");
            
        } catch (SerializationException e) {
            
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void YesStatusRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesStatusRadioButtonActionPerformed
        // TODO add your handling code here;
        VaccineBrandComboBox.setEnabled(true);
    }//GEN-LAST:event_YesStatusRadioButtonActionPerformed

    private void SortingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortingButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table.getModel();
        model.setRowCount(0);
        
        VaccineDao vxd = new VaccineDao();
        Vaccine vx = new Vaccine();
        
        List<Vaccine> vxlist = vxd.findThemAll();
        
        String chosenStatus = (String) SortingComboBox.getSelectedItem();
        
        for (Vaccine v : vxlist) {
            if (v.getVaccinationstatus().equalsIgnoreCase(chosenStatus)) {
                model.insertRow(model.getRowCount(), new Object[]{
                    v.getCitizenId(),
                    v.getFullnames(),
                    v.getPhonenumber(),
                    v.getVaccinationstatus(),
                    v.getVaccinebrand(),
                    v.getVaccinationdate()
                });
            }
        }
    }//GEN-LAST:event_SortingButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton NoStatusRadioButton;
    private javax.swing.JButton SortingButton;
    private javax.swing.JComboBox<String> SortingComboBox;
    private javax.swing.JTable Table;
    private com.toedter.calendar.JDateChooser VaccinationDateField;
    private javax.swing.JComboBox<String> VaccineBrandComboBox;
    private javax.swing.JRadioButton YesStatusRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField citizenIdField;
    private javax.swing.JTextField fullnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField phoneNumberField;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
